# config.yaml
cluster: "sbatch --account={resources.account} \
                --job-name={wildcards.sample}.{rule}.{jobid}.slurm \
                {resources.partition} \
                --time={resources.time_min} \
                --mem={resources.mem_mb} \
                --ntasks-per-node={resources.cpus} \
                --output={wildcards.output_path}/{wildcards.sample}/logs/slurm/{wildcards.sample}.{rule}.{jobid}.slurm.log \
                --error={wildcards.output_path}/{wildcards.sample}/logs/slurm/{wildcards.sample}.{rule}.{jobid}.slurm.log \
                --mail-type=FAIL \
                --mail-user={resources.email}"
                
local-cores: 1
jobs: 100
latency-wait: 60
restart-times: 1
keep-going: True
rerun-incomplete: True
printshellcmds: True
use-conda: True
conda-frontend: mamba
